insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.9682357, 12.6823985, 'Nasce l''industria tessile nel Pordenonese', '1840-02-06', 'Il 6 febbraio 1840 i fratelli Beloz, insieme al socio Blanch di Trieste, acquistano due appezzamenti di terreno incolto nel borgo di Torre, lungo le rive del fiume Noncello, per costruire un impianto manifatturiero per la lavorazione del cotone. Nasce così il primo opificio tessile moderno di Pordenone, destinato a diventare, per oltre un secolo, il settore economico trainante della città.', 'https://www.storiastoriepn.it/le-fasi-costruttive-del-cotonificio-di-torre-di-pordenone-1839-1960/', 'https://i0.wp.com/www.storiastoriepn.it/wp-content/uploads//2023/05/4-MAPPA-IGM-1891-scaled.jpg?resize=1068%2C742&ssl=1');

insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.9429976, 12.6189918, 'A Vienna scoppia la Rivoluzione di marzo', '1848-03-13', 'Il 13 marzo, a Vienna, una folla di studenti universitari si radunò davanti al Palazzo Imperiale chiedendo un governo più liberale, una costituzione e le dimissioni del cancelliere Metternich. L''intervento delle truppe portò a uno scontro violento con cinque manifestanti uccisi, ma il 15 marzo l''imperatore fu costretto ad accettare le dimissioni di Metternich, aprendo la stagione dei moti rivoluzionari in tutto l''Impero asburgico.', null, 'https://upload.wikimedia.org/wikipedia/commons/e/e8/HGM_Revolution_1848_Defil%C3%A9e_der_Nationalgarde_auf_dem_Platz_am_Hof_in_Wien.jpg');

insert into events (draft, lat, lng, title, date, text, url, image)
values (true, 45.9544616, 12.6600413, 'Da Venezia a Pordenone: l''eco della rivolta si diffonde', '1848-03-18', 'La notizia dell''insurrezione di Vienna e delle dimissioni di Metternich accese gli animi anche a Venezia, dove una folla si radunò in Piazza San Marco chiedendo la liberazione di Daniele Manin e degli altri patrioti incarcerati. Il giorno seguente la notizia raggiunse anche Pordenone, proprio nel giorno di mercato, e la città reagì esponendo bandiere tricolori ovunque.', null, 'https://www.loppure.it/wp-content/uploads/2025/06/Screenshot-2025-06-16-130856.png');

insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.9547801, 12.6602208, 'Pordenone si dota di una propria Guardia civica', '1848-03-24', 'Con la proclamazione a Udine del Governo provvisorio del Friuli e la sua annessione alla Repubblica di San Marco, Pordenone visse un momento di fermento politico e istituì una propria guardia civica per garantire l''ordine pubblico. L''esperienza fu però di breve durata: l''avanzata delle truppe austriache del generale Nugent riportò rapidamente la città sotto il controllo asburgico e la guardia civica fu sciolta.', null, 'https://www.loppure.it/wp-content/uploads/2025/06/33786-e1749811496573.jpg');

insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.9592954, 12.6576817, 'L''avanzata austriaca segna la fine della rivoluzione veneta nel Pordenonese', '1848-04-30', 'Il 30 aprile le truppe del generale Nugent, dopo aver superato il Tagliamento, stabilirono il quartier generale a Pordenone, concludendo in poco più di un mese l''esperienza rivoluzionaria nel territorio. Molti giovani pordenonesi seguirono comunque il generale La Marmora fino a Venezia per difendere la Repubblica di San Marco, e alcuni di loro caddero nella battaglia di Marghera del 24 maggio 1848.', null, 'https://beniculturali.regione.veneto.it/xway-front/application/crv/engine/crv.jsp?verbo=attach&db=crv_back&id=giw8MFprnpaFFX2xbjHvvJqk6ZqtlEOPdJT%2FEJKstQuEYC6BhKflzXluRPqwxUBE.jpg');

insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.9592954, 12.6576817, 'L''imperatore Francesco Giuseppe visita Pordenone', '1852-10-07', 'Il giovane imperatore Francesco Giuseppe visitò il Friuli occidentale, soggiornando cinque giorni a Pordenone e assistendo a due rappresentazioni dell''Ernani al Teatro Sociale. Soddisfatto dell''accoglienza ricevuta, elevò Pordenone al rango di Congregazione municipale, permettendole di nominare un podestà e quattro assessori al posto della precedente Deputazione comunale.', null, 'https://www.loppure.it/wp-content/uploads/2025/06/6280cc96-07aa-4903-b4a3-2a08ed7ba557-1.png');

insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.9564911, 12.6542229, 'Urbanistica e priorità moderne: una strada per la Stazione', '1853-04-22', 'Il nuovo Consiglio comunale di Pordenone deliberò l''ampliamento della Porta della Bossina, ma la crescente importanza della nuova linea ferroviaria impose altre priorità. Il Consiglio destinò così 62.000 lire alla realizzazione di una nuova strada d''accesso alla stazione, completata in tempi record e oggi nota come Viale Mazzini, mentre i lavori alla Porta non furono mai avviati.', null, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/ee/f6/80/scala-della-bossina-o.jpg?w=1200&h=1200&s=1');

insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.9564911, 12.6542229, 'Viene inaugurata la ferrovia Treviso-Pordenone', '1855-04-30', 'Il 30 aprile 1855 fu inaugurato il tronco ferroviario Treviso–Pordenone, segnando un momento storico per lo sviluppo della città. L''evento fu celebrato con grande entusiasmo: concerti della banda militare, una solenne funzione religiosa, l''illuminazione festosa dell''intero paese e una festa da ballo al Teatro Sociale.', null, 'https://www.loppure.it/wp-content/uploads/2025/06/f533159f-e812-4d7c-9012-999650460321.png');

insert into events (draft, lat, lng, title, date, text, url, image)
values (true, 45.9569003, 12.6606626, 'Una nuova sede per l''Ospedale, l''arrivo del telegrafo e i "prestiti volontari" all''Impero', '1858-01-01', 'Nel 1858 l''Ospedale di Pordenone fu trasferito in un nuovo edificio adiacente alla Chiesa del Cristo ed entrò in funzione l''ufficio telegrafico statale. Nello stesso periodo, il governo imperiale impose al Regno Lombardo-Veneto un contributo straordinario di guerra, riscosso a Pordenone sotto forma di un "prestito volontario" la cui volontarietà, come si disse ironicamente all''epoca, era solo quella del governo.', null, 'https://www.loppure.it/wp-content/uploads/2025/06/03b91dc8-c924-4e56-b397-423662fa226f.png');

insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.922011, 12.6689996, 'Il Friuli e Pordenone tra plebisciti, esilio volontario e patriottismo', '1860-01-16', 'Dopo la pace di Zurigo, anche Pordenone partecipò al plebiscito segreto promosso dai Comuni friulani per l''annessione al Regno di Sardegna, i cui risultati furono presentati a Cavour il 16 gennaio 1860. Non potendo ottenere l''annessione immediata, molti pordenonesi rimasero esuli volontari, unendosi ai volontari garibaldini o all''esercito regio in vista di nuovi scontri.', null, null);

insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.9575391, 12.6659157, 'Viene repressa una manifestazione patriottica per il primo Parlamento italiano', '1861-02-18', 'In occasione dell''apertura del primo Parlamento del Regno d''Italia, il Comitato segreto patriottico di Pordenone organizzò una manifestazione simbolica a cui, con grande sorpresa, partecipò anche il podestà Giovanni Battista Poletti con tre assessori. La reazione austriaca fu rapida: il Municipio venne sospeso, gli amministratori multati e alcuni cittadini ritenuti promotori dell''iniziativa furono arrestati ed esiliati in Moravia.', null, null);

insert into events (draft, lat, lng, title, date, text, url, image)
values (true, 45.9544616, 12.6600413, 'L''arrivo dei soldati italiani e la "giunta rivoluzionaria"', '1866-07-19', 'Il 19 luglio 1866 arrivarono a Pordenone i primi soldati dell''esercito italiano, accolti dalla popolazione con gioia. Nel vuoto d''autorità seguito al ritiro delle truppe austriache, un gruppo di cittadini costituì una sedicente "giunta governativa distrettuale" che occupò il palazzo comunale, ma la presa di potere fu rapidamente annullata dal Commissario del Re Quintino Sella dopo appena otto giorni.', null, null);

insert into events (draft, lat, lng, title, date, text, url, image)
values (false, 45.9576553, 12.6608913, 'Pordenone, attraverso un plebiscito, viene annessa al Regno d''Italia', '1866-10-21', 'Dopo la pace di Vienna che sanciva il passaggio del Veneto al Regno Sabaudo, il 21 ottobre 1866 si tenne a Pordenone il plebiscito per l''annessione al Regno d''Italia, con un risultato di 2.035 voti favorevoli e nessun contrario. La città festeggiò con un grande ballo mascherato al Teatro Sociale e inviò una delegazione a Padova per rendere omaggio al Re Vittorio Emanuele II.', null, null);
